# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('ScannedBy', models.CharField(blank=True, max_length=50)),
                ('ScannedDate', models.DateField(blank=True)),
                ('InsertedBy', models.CharField(blank=True, max_length=50)),
                ('InsertedDate', models.DateField(blank=True)),
                ('SlideType', models.IntegerField(choices=[(2, b'openslide')])),
                ('UrlPath', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
