# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histoslide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='SlideType',
            field=models.IntegerField(choices=[(2, 'openslide')]),
        ),
    ]
