# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histoslide', '0002_auto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['UrlPath']},
        ),
    ]
